export enum ENVEnum {
  NODE_ENV = 'NODE_ENV',
  DATABASE_URL = 'DATABASE_URL',

  PORT = 'PORT',
  BASE_URL = 'BASE_URL',

  FRONTEND_URL = 'FRONTEND_URL',

  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  RESET_TOKEN_EXPIRES_IN = 'RESET_TOKEN_EXPIRES_IN',
  MAIL_USER = 'MAIL_USER',
  MAIL_PASS = 'MAIL_PASS',

  SUPER_ADMIN_EMAIL = 'SUPER_ADMIN_EMAIL',
  SUPER_ADMIN_PASS = 'SUPER_ADMIN_PASS',

  OAUTH_CLIENT_ID = 'OAUTH_CLIENT_ID',
  OAUTH_CLIENT_SECRET = 'OAUTH_CLIENT_SECRET',

  STRIPE_SECRET_KEY = 'STRIPE_SECRET_KEY',
  STRIPE_WEBHOOK_SECRET = 'STRIPE_WEBHOOK_SECRET',

  PAYPAL_CLIENT_SECRET = 'PAYPAL_CLIENT_SECRET',
  PAYPAL_CLIENT_ID = 'PAYPAL_CLIENT_ID',
  PAYPAL_URL = 'PAYPAL_URL',
  PAYPAL_ENVIRONMENT = 'PAYPAL_ENVIRONMENT',
  // -------------------firebase ------------------
  FIREBASE_PROJECT_ID = 'FIREBASE_PROJECT_ID',
  FIREBASE_CLIENT_EMAIL = 'FIREBASE_CLIENT_EMAIL',
  FIREBASE_PRIVATE_KEY = 'FIREBASE_PRIVATE_KEY',

  // -------------------agora ------------------
  AGORA_CUSTOMER_ID = 'AGORA_CUSTOMER_ID',
  AGORA_SECRET = 'AGORA_SECRET',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  BUCKET_NAME = 'BUCKET_NAME',
}
